#!/bin/bash

# Stream low quality to youtube
#raspivid -o - -t 0 -vf -hf -fps 25 -b 4000000 | ffmpeg -re -ar 44100 -ac 2 -acodec pcm_s16le -f s16le -ac 2 -i /dev/zero -f h264 -i - -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -f flv rtmp://a.rtmp.youtube.com/live2/$KEY

# Broken = ALSA buffer xrun
#raspivid -o - -t 0 -vf -hf -fps 25 -b 4000000 | ffmpeg -re -f alsa -i plughw:1 -f h264 -i - -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -f flv rtmp://a.rtmp.youtube.com/live2/$KEY

# Broken = ALSA buffer xrun
#raspivid -o - -t 0 -vf -hf -fps 25 -b 4000000 | ffmpeg -re -acodec pcm_s16le -f alsa -i plughw:1 -f h264 -i - -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -f flv rtmp://a.rtmp.youtube.com/live2/$KEY

# Broken = ALSA buffer xrun
# raspivid -o - -t 0 -vf -hf -fps 25 -b 4000000 | ffmpeg -re -f alsa -async 1 -i plughw:1 -f h264 -i - -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -f flv rtmp://a.rtmp.youtube.com/live2/$KEY

# Broken = ALSA buffer xrun
# raspivid -o - -t 0 -vf -hf -fps 25 -b 4000000 | ffmpeg -re -f alsa -i plughw:1 -f h264 -i - -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -b:a 64k -b:v 64k -bufsize 64k -f flv rtmp://a.rtmp.youtube.com/live2/$KEY

# Using wall clock to sync
# Broken = ALSA buffer xrun
#raspivid -o - -t 0 -vf -hf -fps 25 -b 4000000 | ffmpeg -use_wallclock_as_timestamps 1 -re -f alsa -i plughw:1 -f h264 -re -i - -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -f flv rtmp://a.rtmp.youtube.com/live2/$KEY

# --------------------------------------------------------------------------------
# Below configs are all working but with different speeds
# --------------------------------------------------------------------------------

# |   Bytes |   Mbps | Works | Quality |
# |         | upload |       |         |
# |---------+--------+-------+---------|
# | 4000000 |    4.3 | y     | good    |
# | 2000000 |    2.1 | y     | good    |
# | 1000000 |    1.2 | y     | good    |
# |  750000 |    1.0 | y     | medium  |
# |  500000 |    0.6 | y     | poor    |
BYTES=1000000

# # Using wall clock to sync with no -re
# # WORKS!!! (4.3Mbps upload)
# raspivid -o - -t 0 -vf -hf -fps 25 -b 4000000 | ffmpeg -use_wallclock_as_timestamps 1 -f alsa -i plughw:1 -f h264 -i - -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -f flv rtmp://a.rtmp.youtube.com/live2/$KEY

# Using wall clock to sync with no -re
# WORKS!!!
raspivid -o - -t 0 -fps 25 -b $BYTES | ffmpeg -use_wallclock_as_timestamps 1 -f alsa -i plughw:1 -f h264 -i - -vcodec copy -acodec aac -ab 128k -g 50 -strict experimental -f flv rtmp://a.rtmp.youtube.com/live2/$KEY

